add solution for lection1 task1
js-tasks-ru/htmlcss-20220414_phpwork pull request #4
Opened 2022-04-20 08:27 UTC by acidworm

2022-04-20 08:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-20 13:49 UTC, GSemikozov requested changes

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: .2em;
марджины на уровне блока не задаем )

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: .2em;
не хватает паддингов

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: .2em;
а также стилей описывающих оформление текста

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:disabled {transition: none; opacity: 0.5; cursor: not-allowed;}
вместо cursor: not-allowed советую использовать pointer-events: none

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary, .button_primary:disabled:hover {background-color: #4263EB;}
у .button_primary:disabled не должно быть hover-а, пользователь не должен иметь возможность взаимодействовать с disabled элементом, что достигается добавлением pointer-events: none

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary, .button_primary:disabled:hover {background-color: #4263EB;}
и ниже тоже поправить

2022-04-20 13:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate:hover {border: 1px solid #212429;}
можно описать только то что реально меняется - border-color: #212429;

2022-04-21 17:26 UTC, acidworm commented on 03-lection1/01-button/button.css
> +    margin: .2em;
добавил паддинг, установил минимальные размеры кнопки через min-width и min-height
добавил стили для текста

2022-04-21 17:26 UTC, acidworm commented on 03-lection1/01-button/button.css
> +.button:disabled {transition: none; opacity: 0.5; cursor: not-allowed;}
заменил на pointer-events: none

2022-04-21 17:26 UTC, acidworm commented on 03-lection1/01-button/button.css
> +.button_primary, .button_primary:disabled:hover {background-color: #4263EB;}
убрал :disabled:hover

2022-04-22 08:48 UTC, GSemikozov requested changes

2022-04-22 08:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 1em;
1em = 16px, что не соответствует макету. По дизайну - padding: 15px 15px 14px

2022-04-22 08:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: .95rem;
а здесь почему rem?) 1rem = 16px, поэтому тогда не .95 а 1

2022-04-22 08:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
здесь как раз таки достаточно height (мы не хотим чтобы кнопка могла расти в высоту)

2022-04-22 08:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: .95rem;
и еще не хватает font-family

2022-04-22 08:48 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate {background-color: var(--white); color: var(--black); border: 1px solid var(--grey-3);}
поскольку здесь добавляется border, на уровне .button лучше задать box-sizing: border-box

2022-04-24 16:22 UTC, acidworm commented on 03-lection1/01-button/button.css
> +    padding: 1em;
исправил

2022-04-24 16:22 UTC, acidworm commented on 03-lection1/01-button/button.css
> +    font-size: .95rem;
исправил

2022-04-24 16:22 UTC, acidworm commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
исправил

2022-04-24 16:24 UTC, acidworm commented on 03-lection1/01-button/button.css
> +.button_alternate {background-color: var(--white); color: var(--black); border: 1px solid var(--grey-3);}
добавил

2022-04-24 18:08 UTC, GSemikozov approved these changes

2022-04-24 18:08 UTC, merged